version: '3.1'
services:
  stats-server:
    build: ./ewm-stat
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/ExploreWithMeStat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    depends_on:
      - stat-db
  stat-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ExploreWithMeStat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  ewm-service:
    build: ./ewm-main
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ExploreWithMe
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - stat.url=http://stats-server:9090
    depends_on:
      - ewm-db
  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ExploreWithMe
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
