DROP TABLE IF EXISTS EVENTS, CATEGORIES, LOCATIONS, USERS, PARTICIPATIONS_REQUESTS, COMPILATIONS, EVENTS_COMPILATIONS;

CREATE TABLE IF NOT EXISTS CATEGORIES
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS LOCATIONS
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT8 NOT NULL,
    lon FLOAT8 NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(100) NOT NULL,
    email VARCHAR(250) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS COMPILATIONS
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN      NOT NULL,
    tittle VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS EVENTS
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY             NOT NULL,
    tittle             VARCHAR(250)                                        NOT NULL,
    annotations        VARCHAR(250)                                        NOT NULL,
    category_id        BIGINT REFERENCES CATEGORIES (id) ON DELETE CASCADE NOT NULL,
    description        VARCHAR(1000)                                       NOT NULL,
    created            TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    published          TIMESTAMP WITHOUT TIME ZONE,
    location_id        BIGINT REFERENCES LOCATIONS (id) ON DELETE CASCADE  NOT NULL,
    paid               BOOLEAN                                             NOT NULL,
    participant_limit  BIGINT                                              NOT NULL,
    request_moderation BOOLEAN                                             NOT NULL,
    confirmed_requests INTEGER,
    initiator_id       BIGINT REFERENCES USERS (id) ON DELETE CASCADE      NOT NULL,
    state              BIGINT,
    views              BIGINT
);

CREATE TABLE IF NOT EXISTS EVENTS_COMPILATIONS
(
    compilation_id BIGINT REFERENCES COMPILATIONS(id),
    event_id       BIGINT REFERENCES EVENTS(id),
    primary key (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS PARTICIPATIONS_REQUESTS
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP NOT NULL,
    event_id     BIGINT REFERENCES EVENTS (id) ON DELETE CASCADE,
    requester_id BIGINT REFERENCES USERS (id) ON DELETE CASCADE,
    status       BOOLEAN   NOT NULL
);